services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads_data:/app/public/uploads
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: shopync
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopync"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  uploads_data: